import { lazy } from 'react';

export default [
  {
    path: '/base64',
    nameKey: 'base64.mainTitle',
  descKey: 'base64.cardDescription',
  pageTitleKey: 'base64.pageTitle',
  pageDescriptionKey: 'base64.pageDescription',
    Component: lazy(() => import('./components/tools/Base64Tool')),
  },
  {
    path: '/diff',
    nameKey: 'Diff',
  descKey: 'Text Comparison Tool',
  pageTitleKey: 'diff.pageTitle',
  pageDescriptionKey: 'diff.pageDescription',
    Component: lazy(() => import('./components/tools/DiffTool')),
  },
  {
    path: '/json-formatter',
    nameKey: 'JSON Formatter',
  descKey: 'JSON Format/Minify Tool',
  pageTitleKey: 'json-formatter.pageTitle',
  pageDescriptionKey: 'json-formatter.pageDescription',
    Component: lazy(() => import('./components/tools/JsonFormatter')),
  },
  {
    path: '/url-encoder',
    nameKey: 'URL Encoder/Decoder',
  descKey: 'URL Encode/Decode Tool',
  pageTitleKey: 'url-encoder.pageTitle',
  pageDescriptionKey: 'url-encoder.pageDescription',
    Component: lazy(() => import('./components/tools/UrlEncoder')),
  },
  {
    path: '/timestamp',
    nameKey: 'Timestamp Converter',
  descKey: 'Unix Timestamp Converter',
  pageTitleKey: 'timestamp.pageTitle',
  pageDescriptionKey: 'timestamp.pageDescription',
    Component: lazy(() => import('./components/tools/TimestampConverter')),
  },
  {
    path: '/color-converter',
    nameKey: 'Color Converter',
  descKey: 'RGB/HEX/HSL Converter',
  pageTitleKey: 'color-converter.pageTitle',
  pageDescriptionKey: 'color-converter.pageDescription',
    Component: lazy(() => import('./components/tools/ColorConverter')),
  },
  {
    path: '/regex-tester',
    nameKey: 'Regex Tester',
  descKey: 'Regex Testing Tool',
  pageTitleKey: 'regex-tester.pageTitle',
  pageDescriptionKey: 'regex-tester.pageDescription',
    Component: lazy(() => import('./components/tools/RegexTester')),
  },
  {
    path: '/text-analyzer',
    nameKey: 'Text Analyzer',
  descKey: 'Text Statistics Tool',
  pageTitleKey: 'text-analyzer.pageTitle',
  pageDescriptionKey: 'text-analyzer.pageDescription',
    Component: lazy(() => import('./components/tools/TextAnalyzer')),
  },
  {
    path: '/hash-generator',
    nameKey: 'Hash Generator',
  descKey: 'MD5/SHA Hash Generator',
  pageTitleKey: 'hash-generator.pageTitle',
  pageDescriptionKey: 'hash-generator.pageDescription',
    Component: lazy(() => import('./components/tools/HashGenerator')),
  },
  {
    path: '/text-processor',
    nameKey: 'Text Processor',
  descKey: 'Text Processing Tool',
  pageTitleKey: 'text-processor.pageTitle',
  pageDescriptionKey: 'text-processor.pageDescription',
    Component: lazy(() => import('./components/tools/TextProcessor')),
  },
  {
    path: '/uuid-generator',
    nameKey: 'UUID Generator',
  descKey: 'UUID Generator Tool',
  pageTitleKey: 'uuid-generator.pageTitle',
  pageDescriptionKey: 'uuid-generator.pageDescription',
    Component: lazy(() => import('./components/tools/UUIDGenerator')),
  },
  {
    path: '/markdown-preview',
    nameKey: 'Markdown Preview',
  descKey: 'Markdown Preview Tool',
  pageTitleKey: 'markdown-preview.pageTitle',
  pageDescriptionKey: 'markdown-preview.pageDescription',
    Component: lazy(() => import('./components/tools/MarkdownPreview')),
  },
  {
    path: '/csv-converter',
    nameKey: 'CSV ↔ JSON Converter',
  descKey: 'CSV to JSON Converter',
  pageTitleKey: 'csv-converter.pageTitle',
  pageDescriptionKey: 'csv-converter.pageDescription',
    Component: lazy(() => import('./components/tools/CsvConverter')),
  },
  {
    path: '/jwt-decoder',
    nameKey: 'JWT Decoder',
  descKey: 'JWT Token Decoder',
  pageTitleKey: 'jwt-decoder.pageTitle',
  pageDescriptionKey: 'jwt-decoder.pageDescription',
    Component: lazy(() => import('./components/tools/JwtDecoder')),
  },
  {
    path: '/qr-generator',
    nameKey: 'QR Code Generator',
  descKey: 'QR Code Generator Tool',
  pageTitleKey: 'qr-generator.pageTitle',
  pageDescriptionKey: 'qr-generator.pageDescription',
    Component: lazy(() => import('./components/tools/QrGenerator')),
  },
  {
    path: '/image-compressor',
    nameKey: 'Image Compressor',
  descKey: 'Online Image Compressor',
  pageTitleKey: 'image-compressor.pageTitle',
  pageDescriptionKey: 'image-compressor.pageDescription',
    Component: lazy(() => import('./components/tools/ImageCompressor')),
  },
  {
    path: '/unicode-converter',
    nameKey: 'Unicode Converter',
  descKey: 'Chinese Unicode Converter',
  pageTitleKey: 'unicode-converter.pageTitle',
  pageDescriptionKey: 'unicode-converter.pageDescription',
    Component: lazy(() => import('./components/tools/UnicodeConverter')),
  },
  {
    path: '/cron-parser',
    nameKey: 'Cron Expression Converter',
  descKey: 'Cron Expression Linux/Spring Converter Tool',
  pageTitleKey: 'cron-parser.pageTitle',
  pageDescriptionKey: 'cron-parser.pageDescription',
    Component: lazy(() => import('./components/tools/CronParser')),
  },
  {
    path: '/image-watermark',
    nameKey: 'Image Watermark',
  descKey: 'Add watermark to image',
  pageTitleKey: 'image-watermark.pageTitle',
  pageDescriptionKey: 'image-watermark.pageDescription',
    Component: lazy(() => import('./components/tools/WatermarkTool')),
  },
  {
    path: '/password-generator',
    nameKey: 'Password Generator',
  descKey: 'Secure Password Generator',
  pageTitleKey: 'password-generator.pageTitle',
  pageDescriptionKey: 'password-generator.pageDescription',
    Component: lazy(() => import('./components/tools/PasswordGenerator')),
  },
];