# Cloudflare Workers 配置文件

name = "url-shortener"
compatibility_date = "2024-03-01"
main = "src/index.js"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "URL_SHORTENER_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 环境变量
[vars]
ENVIRONMENT = "production"
BASE_URL = "https://short.ly"
MAX_URL_LENGTH = 2000
DEFAULT_EXPIRE_DAYS = 30

# 路由配置
[[routes]]
pattern = "short.ly/*"
zone_name = "short.ly"

# 触发器配置
[triggers]
crons = ["0 2 * * *"]  # 每日凌晨2点清理过期链接