# Generated by Django 5.2.4 on 2025-07-16 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, verbose_name="会话ID")),
                ("tool_name", models.CharField(max_length=50, verbose_name="工具名称")),
                ("parameters", models.JSONField(verbose_name="参数")),
                (
                    "result_preview",
                    models.TextField(blank=True, max_length=200, verbose_name="结果预览"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户历史",
                "verbose_name_plural": "用户历史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, unique=True, verbose_name="会话ID"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "亮色"), ("dark", "暗色")],
                        default="light",
                        max_length=10,
                        verbose_name="主题",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh-hans", "中文"), ("en", "English")],
                        default="zh-hans",
                        max_length=10,
                        verbose_name="语言",
                    ),
                ),
                ("favorite_tools", models.JSONField(default=list, verbose_name="收藏工具")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
            },
        ),
        migrations.CreateModel(
            name="ToolUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=50, verbose_name="工具名称")),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="最后使用时间"),
                ),
            ],
            options={
                "verbose_name": "工具使用统计",
                "verbose_name_plural": "工具使用统计",
                "unique_together": {("tool_name",)},
            },
        ),
    ]
